title: "Siddhant Gayakwad"
email: ""
description: "DevOps Engineer | AWS • Docker • Kubernetes • CI/CD"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://siddhant-gayakwad.github.io"

# Build settings
markdown: kramdown
theme: minima

# Navigation links (used in layout)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
