title: "Siddhant Gayakwad"
email: "siddhantgayakwad@gmail.com"
description: "DevOps Engineer | AWS • Docker • Kubernetes • CI/CD"
baseurl: ""
url: "https://siddhant-gayakwad.github.io"

# Social links used in templates
github: "https://github.com/siddhant-gayakwad"
linkedin: "https://www.linkedin.com/in/siddhant-gayakwad-524524191/"
resume: "/assets/resume/Resumes_Devops_2026.pdf"

# Build settings
markdown: kramdown

# Navigation links (used in layout)
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Resume"
    url: "/resume"
